### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException: rs.getString(i + 1) must not be null

### ISSUE THREAD

**Issue by mdeniz63** [saro-lab/solr-db-importer#1]
Exception in thread "main" java.lang.NullPointerException: rs.getString(i + 1) must not be null
        at domain.dbimport.ImportData.toJson(ImportData.kt:51)
        at domain.dbimport.ImportData.handle(ImportData.kt:26)
        at app.SolrDataImporterKt$main$1.invoke(SolrDataImporter.kt:21)
        at app.SolrDataImporterKt$main$1.invoke(SolrDataImporter.kt:20)
        at domain.dbconn.DbConnector$Companion.conn(DbConnector.kt:14)
        at app.SolrDataImporterKt.main(SolrDataImporter.kt:20)
        at app.SolrDataImporterKt.main(SolrDataImporter.kt)

**Comment by mdeniz63** [comment]
without schemaless core I only write http://localhost:8983/solr/<core_name>

**Comment by marker-seoul** [comment]
i fixed that issue

https://github.com/saro-lab/solr-db-importer/releases/tag/1.1

thank you

**Comment by mdeniz63** [comment]
Thank you its working
