### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by mdeniz63** [saro-lab/solr-db-importer#2]
update row 782000
update row 783000
update row 784000
update row 785000
update row 786000
update row 787000
update row 788000
update row 789000
update row 790000
update row 791000
update row 792000
update row 793000
update row 794000
update row 795000
update row 796000
update row 797000
update row 798000
update row 799000
update row 800000
update row 801000
update row 802000
update row 803000
update row 804000
update row 805000
update row 806000
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
        at java.base/java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:120)
        at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:95)
        at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:156)
        at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
        at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:303)
        at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:281)
        at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
        at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:135)
        at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:226)
        at java.base/java.io.Writer.write(Writer.java:249)
        at org.springframework.util.StreamUtils.copy(StreamUtils.java:147)
        at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:126)
        at org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:44)
        at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227)
        at org.springframework.web.client.RestTemplate$HttpEntityRequestCallback.doWithRequest(RestTemplate.java:991)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:774)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
        at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:437)
        at domain.solrconn.SolrConnector.update(SolrConnector.kt:24)
        at domain.dbimport.ImportData.handle(ImportData.kt:29)
        at app.SolrDataImporterKt$main$1.invoke(SolrDataImporter.kt:21)
        at app.SolrDataImporterKt$main$1.invoke(SolrDataImporter.kt:20)
        at domain.dbconn.DbConnector$Companion.conn(DbConnector.kt:14)
        at app.SolrDataImporterKt.main(SolrDataImporter.kt:20)
        at app.SolrDataImporterKt.main(SolrDataImporter.kt)

**Comment by mdeniz63** [comment]
When I tried to import big data with clob and varchar2 from oracle to i get solr java heap size error

**Comment by marker-seoul** [comment]
@mdeniz63 
Can you try reducing the bulkExecuteRowCount value of xml to around 10?

**Comment by mdeniz63** [comment]
Exception in thread "main" java.lang.RuntimeException: bulkExecuteRowCount must be greater than 100 and less than 100000.
        at domain.conf.Conf.validate(Conf.kt:25)
        at domain.conf.ReadConf$Companion.handle(ReadConf.kt:21)
        at app.SolrDataImporterKt.main(SolrDataImporter.kt:17)
        at app.SolrDataImporterKt.main(SolrDataImporter.kt)

I will try 100.

**Comment by marker-seoul** [comment]
i fixed range of bulkExecuteRowCount 

https://github.com/saro-lab/solr-db-importer/releases/tag/1.2

**Comment by mdeniz63** [comment]
1.2 version is better  I can updated 764000 row but again heap size error

update row 760000
update row 761000
update row 762000
update row 763000
update row 764000
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.lang.StringCoding.encodeUTF8_UTF16(StringCoding.java:932)
        at java.base/java.lang.StringCoding.encodeUTF8(StringCoding.java:907)
        at java.base/java.lang.StringCoding.encode(StringCoding.java:449)
        at java.base/java.lang.String.getBytes(String.java:964)
        at org.springframework.http.converter.StringHttpMessageConverter.getContentLength(StringHttpMessageConverter.java:102)
        at org.springframework.http.converter.StringHttpMessageConverter.getContentLength(StringHttpMessageConverter.java:44)
        at org.springframework.http.converter.AbstractHttpMessageConverter.addDefaultHeaders(AbstractHttpMessageConverter.java:260)
        at org.springframework.http.converter.StringHttpMessageConverter.addDefaultHeaders(StringHttpMessageConverter.java:116)
        at org.springframework.http.converter.StringHttpMessageConverter.addDefaultHeaders(StringHttpMessageConverter.java:44)
        at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:211)
        at org.springframework.web.client.RestTemplate$HttpEntityRequestCallback.doWithRequest(RestTemplate.java:991)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:774)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
        at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:437)
        at domain.solrconn.SolrConnector.update(SolrConnector.kt:24)
        at domain.dbimport.ImportData.handle(ImportData.kt:29)
        at app.SolrDataImporterKt$main$1.invoke(SolrDataImporter.kt:21)
        at app.SolrDataImporterKt$main$1.invoke(SolrDataImporter.kt:20)
        at domain.dbconn.DbConnector$Companion.conn(DbConnector.kt:14)
        at app.SolrDataImporterKt.main(SolrDataImporter.kt:20)
        at app.SolrDataImporterKt.main(SolrDataImporter.kt)

**Comment by marker-seoul** [comment]
@mdeniz63 
Can you try reducing the bulkExecuteRowCount value of xml to around 10 in 1.2 version

**Comment by mdeniz63** [comment]
I have tried but always memory usage always going up when row count go up and after finish memory its getting error
<img width="317" alt="image" src="https://user-images.githubusercontent.com/28572223/207921758-1ea198eb-433b-46b5-ab30-57b49011bbc0.png">

update row 774900
update row 775000
update row 775100
update row 775200
update row 775300
update row 775400
update row 775500
update row 775600
update row 775700
update row 775800
update row 775900
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
        at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
        at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:538)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:178)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:89)
        at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:573)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:208)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:89)
        at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:86)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3499)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3516)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3515)
        at domain.solrconn.SolrConnector.update(SolrConnector.kt:22)
        at domain.dbimport.ImportData.handle(ImportData.kt:29)
        at app.SolrDataImporterKt$main$1.invoke(SolrDataImporter.kt:21)
        at app.SolrDataImporterKt$main$1.invoke(SolrDataImporter.kt:20)
        at domain.dbconn.DbConnector$Companion.conn(DbConnector.kt:14)
        at app.SolrDataImporterKt.main(SolrDataImporter.kt:20)
        at app.SolrDataImporterKt.main(SolrDataImporter.kt)

**Comment by mdeniz63** [comment]
I have succeded with java memory parameters

update row 790000
update row 800000
update row 810000
update row 820000
update row 829981 - done
[root@solr1 solr]# java -Xms5g -Xmx10g -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -jar solr-db-importer-1.2.jar

But it is best to test and choose best parameters for running.

Thanks for your care

**Comment by marker-seoul** [comment]
@mdeniz63 1.3 version.. (StringBuilder version)
...
thank you..
