### ISSUE TITLE
oom occurrence problem in large-capacity RestTemplate

### ISSUE THREAD

**Issue by marker-seoul** [saro-lab/solr-db-importer#3]
changed subject

// prev
## OutOfMemoryError 
- java -Xms5g -Xmx10g -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -jar solr-db-importer-1.2.jar
- https://github.com/saro-lab/solr-db-importer/issues/2

## output error fields/req

**Comment by mdeniz63** [comment]
I have tested new 1.3 jar with bulkExecuteRowCount = 10000 

update row 775731
update row 775814
Exception in thread "Keep-Alive-Timer" java.lang.OutOfMemoryError: Java heap space
        at java.base/sun.net.www.http.KeepAliveCache.run(KeepAliveCache.java:226)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at java.base/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:161)
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

**Comment by marker-seoul** [comment]
@mdeniz63 
https://github.com/saro-lab/solr-db-importer/releases/tag/1.4

I tried disabling the http request buffer.
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/client/SimpleClientHttpRequestFactory.html#setBufferRequestBody(boolean)
