### ISSUE TITLE
Encountered the following error:

### ISSUE THREAD

**Issue by anshad14** [saro-lab/solr-db-importer#5]
**Exception in thread "main" org.springframework.web.client.HttpClientErrorException$MethodNotAllowed: 405 Method Not Allowed: "HTTP ERROR 405 HTTP method POST is not supported by this URL
URI: /solr/
STATUS: 405
MESSAGE: HTTP method POST is not supported by this URL
SERVLET: LoadAdminUI"**

When attempting to execute the command java -jar solr-db-importer-1.4.jar, I encountered an error that ,

**Solr DB importer**
github: https://github.com/saro-lab/solr-db-importer
----------------------------------------------------
*Exception in thread "main" org.springframework.web.client.HttpClientErrorException$MethodNotAllowed: 405 Method Not Allowed: "HTTP ERROR 405 HTTP method POST is not supported by this URL<EOL>URI: /solr/<EOL>STATUS: 405<EOL>MESSAGE: HTTP method POST is not supported by this URL<EOL>SERVLET: LoadAdminUI<EOL>"
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:117)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:437)
	at domain.solrconn.SolrConnector.update(SolrConnector.kt:26)
	at domain.dbimport.ImportData.handle(ImportData.kt:31)
	at app.SolrDataImporterKt$main$1.invoke(SolrDataImporter.kt:21)
	at app.SolrDataImporterKt$main$1.invoke(SolrDataImporter.kt:20)
	at domain.dbconn.DbConnector$Companion.conn(DbConnector.kt:14)
	at app.SolrDataImporterKt.main(SolrDataImporter.kt:20)
	at app.SolrDataImporterKt.main(SolrDataImporter.kt)*
	
How can i fix this ? my  solr version is 9.2.1

**Comment by marker-seoul** [comment]
1. Please check the operation of Solr.
2. Please verify if the Solr schema at solrSchemaUrl is correct.
For example, if it is set on the default port and the schema is dev_gs_forum, the following should be displayed when accessing it through a browser.

![image](https://github.com/saro-lab/solr-db-importer/assets/15857631/0536f681-cf75-41c0-b933-ed819ae3a413)


Please check the configuration of db-import.xml.
